### ISSUE TITLE
Setting a function as "conjugate-quadratic"

### ISSUE THREAD

**Issue by lostella** [lostella/libForBES#24]
When the function QuadraticOverAffine(Q, q, A, b) is defined, then its conjugate is quadratic as long as d'Qd > 0 for all d in the subspace {x : Ax = b}. Now when solving 

```
    minimize f(x) + g(z) subject to Ax + Bz = b
```

we will assume that f is strongly convex (this will be our contract with the user, so to speak) and therefore if f = QuadraticOverAffine(Q, q, A, b) then necessarily f\* will be quadratic. This should be easily detectable: just like we mark whether or not a function f defines the gradient of the conjugate and then set that ConjugateFunction(f) defines the gradient when constructing it, it would be desirable to mark whether f is "conjugate-quadratic" and set that ConjugateFunction(f) is quadratic.

**Comment by alphaville** [comment]
Done (I think)
